[versions]
gradleplugin = "7.3.1"
kotlin = "1.7.20"

core = "1.9.0"
appcompat = "1.5.1"
material = "1.7.0"
constraintlayout = "2.1.4"

junit4 = "4.13.2"
test-junit = "1.1.3"
test-espresso = "3.4.0"

[libraries]
core = { module = "androidx.core:core-ktx", version.ref = "core" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraint-layout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }

junit4 = { module = "junit:junit", version.ref = "junit4" }
test-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "test-junit" }
test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "test-espresso" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
android-library = { id = "com.android.library", version.ref = "gradleplugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }